### ISSUE TITLE
Element type is invalid on SelectionArea component

### ISSUE THREAD

**Issue by Alecell** [simonwep/selection#183]
#### What is the problem?
I'm getting the `Element type is invalid` error when use the SelectionArea component.

#### What is the current behavior?
The component does not render and I got this error below
```shell
Check your code at _app.page.tsx:36.
    at App (webpack-internal:///./src/pages/_app.page.tsx:15:94)
    at StyleRegistry (/home/alecell/projects/alecell/apps/mangale/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/home/alecell/projects/alecell/apps/mangale/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/home/alecell/projects/alecell/apps/mangale/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/home/alecell/projects/alecell/apps/mangale/node_modules/next/dist/server/render.js:614:21)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/alecell/projects/alecell/apps/mangale/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
```

thats the line 36:
![image](https://user-images.githubusercontent.com/13935760/201445171-c862bef2-291a-4e69-9376-3305a766208c.png)

#### Please provide the steps to reproduce and create a [CodeSandbox](https://codesandbox.io/).
Just copied the [usage template](https://github.com/Simonwep/selection/tree/master/packages/react#usage) and add it to my app 

#### What is the expected behavior?
Component should render as expected

#### Your environment:
```
NextJS: 12.3.1
Version (@viselect/react): 3.0.0 and 3.1.1
Browser:  Chrome 107.0.5304.107
OS:  Windows with WSL
React: 18.2.0
React DOM: 18.2.0 
```

**Comment by Simonwep** [comment]
Could you please provide a reproduction on CodeSandbox for me to test it? The CI build for the react package is succeeding on my end...

**Comment by simonwep** [comment]
Closing due to inactivity.
